language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_91c6012413a9_key -iv $encrypted_91c6012413a9_iv
  -in test/testServiceAccountCredentials.json.enc -out test/testServiceAccountCredentials.json
  -d
- npm i -g npm
