language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
before_install:
- openssl aes-256-cbc -K $encrypted_91c6012413a9_key -iv $encrypted_91c6012413a9_iv
  -in testServiceAccountCredentials.json.enc -out testServiceAccountCredentials.json
  -d
- npm i -g npm
